import type { EventoStreaming } from '../../../nucleo/chat/EventoStreaming';
import { ErrorPaginaProveedor } from '../../../nucleo/errores/ErroresAplicacion';
import type { TransporteNavegador } from '../../../plataforma/webbridge/TransporteNavegador';
import { configuracionProveedor } from '../../../configuracion/ConfiguracionProveedores';
import { SupervisorStreamingProveedor } from '../../compartido/SupervisorStreamingProveedor';
import { scriptEstadoStreamingDeepSeek } from '../scripts/estadoStreaming';import type{EstadoStreamingDeepSeek}from'../tipos';import{convertirRegistroHistoria}from'../servicios/ConvertirRegistroHistoria';import{fusionarRespuesta}from'../servicios/FusionarRespuesta';
const dormir=(ms:number)=>new Promise(r=>setTimeout(r,ms));const CFG=configuracionProveedor('deepseek');
export class DeepSeekStreaming{
 constructor(private transporte:TransporteNavegador,private pausa:(ms:number)=>Promise<unknown>=dormir,private ahora:()=>number=Date.now){}
 private async respuestaIndexedDB(id:string){if(!id)return'';const registro=(await this.transporte.evaluar<any>(`new Promise(resolve=>{const q=indexedDB.open('deepseek-chat');q.onerror=()=>resolve(null);q.onsuccess=()=>{const d=q.result;if(!d.objectStoreNames.contains('history-message'))return resolve(null);const g=d.transaction('history-message','readonly').objectStore('history-message').get(${JSON.stringify('__ID__')});g.onerror=()=>resolve(null);g.onsuccess=()=>resolve(g.result??null)}})`.replace('__ID__',id))).value;const c=convertirRegistroHistoria(registro);return c?.mensajes.filter(m=>m.rol==='asistente').at(-1)?.fragmentos.find(f=>f.type==='RESPONSE')?.content??''}
 private async respuestaApi(id:string):Promise<{contenido:string;terminado:boolean}>{if(!id)return{contenido:'',terminado:false};const r=await this.transporte.evaluar<{contenido:string;terminado:boolean}>(`(async()=>{try{const token=JSON.parse(localStorage.getItem('userToken')||'{}').value||'';if(!token)return{contenido:'',terminado:false};const respuesta=await fetch('/api/v0/chat/history_messages?chat_session_id='+encodeURIComponent(${JSON.stringify('__ID__')}),{ headers: { Authorization: 'Bearer ' + token } });if(!respuesta.ok)return{contenido:'',terminado:false};const cuerpo=await respuesta.json();const mensajes=cuerpo?.data?.biz_data?.chat_messages||[];const ultimo=[...mensajes].reverse().find(m=>String(m?.role||'').toUpperCase()==='ASSISTANT');return{contenido:String(ultimo?.content||''),terminado:String(ultimo?.status||'').toUpperCase()==='FINISHED'}}catch{return{contenido:'',terminado:false}}})()`.replace('__ID__',id));const v=r.value;return v&&typeof v.contenido==='string'&&typeof v.terminado==='boolean'?v:{contenido:'',terminado:false}}
 async *observar():AsyncGenerator<EventoStreaming>{const id=(await this.transporte.evaluar<string>("location.pathname.split('/a/chat/s/')[1]?.split('?')[0]?.split('#')[0] || ''")).value??'';let lt='',lr='',sin=0,reintentos=0,fin=0,fallos=0,iteracion=0;const supervisor=new SupervisorStreamingProveedor(CFG,this.ahora());
  while(true){iteracion++;await this.pausa(CFG.intervaloPollingMs);let ev:EstadoStreamingDeepSeek|undefined;try{ev=(await this.transporte.evaluar<EstadoStreamingDeepSeek>(scriptEstadoStreamingDeepSeek())).value;fallos=0}catch{fallos++;if(fallos>=CFG.maxReintentosConsecutivosAntesRecuperar){yield{tipo:'estado',estado:'desconectado',progresoDetectado:false,estrategia:'dom',detalles:`reintento ${fallos}`};await this.transporte.recuperarPestana?.('chat.deepseek.com',id?`https://chat.deepseek.com/a/chat/s/${id}`:undefined)}continue}
   if(!ev){for(const e of supervisor.observar(`vacio:${fallos}`,'desconocido',this.ahora()))yield e;continue}
   if(ev.isError){if(reintentos++<3){await this.transporte.evaluar("document.querySelector('.ds-button--warning')?.click()");await this.pausa(1500);continue}throw new ErrorPaginaProveedor(ev.errorMessage)}
   const think=ev.think??'';const response=ev.response??'';const firma=`${think.length}:${response.length}:${ev.done?1:0}`;for(const e of supervisor.observar(firma,response?'respondiendo':think?'pensando':'esperando_respuesta',this.ahora()))yield e;
   if(think.startsWith(lt)&&think.length>lt.length){yield{tipo:'pensamiento',contenido:think.slice(lt.length)};lt=think}
   const dom=fusionarRespuesta({contenidoActual:lr,contenidoEntrante:response,fuente:'dom',terminado:ev.done});if(dom.contenido.length>lr.length){yield{tipo:'respuesta',contenido:dom.contenido.slice(lr.length)};lr=dom.contenido;sin=0}else if(lr)sin++;
   if(iteracion>10&&iteracion%5===0){const api=await this.respuestaApi(id);const f=fusionarRespuesta({contenidoActual:lr,contenidoEntrante:api.contenido,fuente:'api',terminado:api.terminado});if(f.contenido.length>lr.length){yield{tipo:'respuesta',contenido:f.contenido.slice(lr.length),estrategia:'historial'};lr=f.contenido;sin=0}if(api.terminado&&api.contenido)fin++}
   if(!lr&&iteracion>20&&iteracion%10===0){const respaldo=await this.respuestaIndexedDB(id);if(respaldo){yield{tipo:'respuesta',contenido:respaldo,estrategia:'historial'};yield{tipo:'fin'};return}}
   if(ev.done)fin++;if(lr&&(fin>=20||sin>100)){yield{tipo:'fin'};return}
  }}
}
