export const CAPI_CONFIG = {
  PUERTOS: {
    BRIDGE_BACKEND: 3847,
    WEBBRIDGE_DAEMON: 10086,
  },
  TIMEOUTS_MS: {
    HTTP_SERVER_TIMEOUT: 1_800_000,
    STREAMING_CHUNK_TIMEOUT: 600_000,
    ASENTAMIENTO_ADJUNTO: 2_000,
    INTERVALO_STREAMING: 100,
    INTERVALO_SONDEO_DOM: 200,
    PAUSA_REINTENTO_SERVIDOR: 3_000,
    WEBBRIDGE_COMMAND: 15_000,
    ESTABILIDAD_FIN_QWEN: 4_000,
    ESTABILIDAD_FIN_QWEN_CON_STOP: 10_000,
    ESTABILIDAD_FIN_QWEN_DOM_DONE: 750,
    RESPUESTA_VACIA_QWEN: 30_000,
  },
  LIMITES_ITERACIONES: {
    ESPERA_BOTON_ENVIO: 1500,
    INICIO_RESPUESTA_DOM: 900,
    MAX_SILENCIO_STREAMING: 3000,
    CONFIRMACION_FIN_RESPUESTA: 6,
    MAX_REINTENTOS_SERVIDOR_BUSY: 3,
  },
} as const;
