import type { Database } from 'bun:sqlite';
export type EstadoEjecucionChat='creada'|'preparando'|'enviando'|'enviado'|'pensando'|'esperando_respuesta'|'respondiendo'|'estabilizando'|'completada'|'reconectando'|'estancada'|'requiere_usuario'|'cancelada'|'fallida';
export const ESTADOS_TERMINALES=new Set<EstadoEjecucionChat>(['completada','cancelada','fallida']);
export const ESTADOS_REANUDABLES=new Set<EstadoEjecucionChat>(['reconectando','estancada','requiere_usuario','fallida']);
export interface EjecucionChatDurable {id:string;proyectoLocalId:string;proveedor:string;modelo?:string;conversacionId?:string;estado:EstadoEjecucionChat;promptHash?:string;respuestaParcial:string;pensamientoParcial:string;estrategia?:string;propietarioId:string;pid?:number;hostname?:string;bootId?:string;modo:'foreground'|'background';comandoJson?:string;ultimoProgresoEn:number;ultimoSondeoEn?:number;creadaEn:number;actualizadaEn:number;completadaEn?:number;errorCodigo?:string;errorDetalle?:string;cancelacionSolicitada:boolean;reintentos:number;ultimaSecuencia:number;}
export interface EventoEjecucionChat {ejecucionId:string;secuencia:number;tipo:string;datos:Record<string,unknown>;creadoEn:number;}
const mapear=(r:any):EjecucionChatDurable=>({id:r.id,proyectoLocalId:r.proyecto_local_id,proveedor:r.proveedor,modelo:r.modelo??undefined,conversacionId:r.conversacion_id??undefined,estado:r.estado,promptHash:r.prompt_hash??undefined,respuestaParcial:r.respuesta_parcial??'',pensamientoParcial:r.pensamiento_parcial??'',estrategia:r.estrategia??undefined,propietarioId:r.propietario_id,pid:r.pid??undefined,hostname:r.hostname??undefined,bootId:r.boot_id??undefined,modo:r.modo??'foreground',comandoJson:r.comando_json??undefined,ultimoProgresoEn:r.ultimo_progreso_en,ultimoSondeoEn:r.ultimo_sondeo_en??undefined,creadaEn:r.creada_en,actualizadaEn:r.actualizada_en,completadaEn:r.completada_en??undefined,errorCodigo:r.error_codigo??undefined,errorDetalle:r.error_detalle??undefined,cancelacionSolicitada:!!r.cancelacion_solicitada,reintentos:r.reintentos??0,ultimaSecuencia:r.ultima_secuencia??0});
export class RepositorioEjecucionesChat{
 constructor(private readonly db:Database){}
 crear(e:Omit<EjecucionChatDurable,'respuestaParcial'|'pensamientoParcial'|'ultimoProgresoEn'|'creadaEn'|'actualizadaEn'|'cancelacionSolicitada'|'reintentos'|'ultimaSecuencia'|'modo'> & Partial<Pick<EjecucionChatDurable,'respuestaParcial'|'pensamientoParcial'|'modo'>>,ahora=Date.now()):void{this.db.query(`INSERT INTO ejecuciones_chat_activas(id,proyecto_local_id,proveedor,modelo,conversacion_id,estado,prompt_hash,respuesta_parcial,pensamiento_parcial,estrategia,propietario_id,pid,hostname,boot_id,modo,comando_json,ultimo_progreso_en,creada_en,actualizada_en,cancelacion_solicitada,reintentos,ultima_secuencia) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,0,0,0)`).run(e.id,e.proyectoLocalId,e.proveedor,e.modelo??null,e.conversacionId??null,e.estado,e.promptHash??null,e.respuestaParcial??'',e.pensamientoParcial??'',e.estrategia??null,e.propietarioId,e.pid??null,e.hostname??null,e.bootId??null,e.modo??'foreground',e.comandoJson??null,ahora,ahora,ahora)}
 actualizar(id:string,c:Partial<EjecucionChatDurable>,ahora=Date.now()):void{const a=this.obtener(id);if(!a)return;const n={...a,...c};this.db.query(`UPDATE ejecuciones_chat_activas SET modelo=?,conversacion_id=?,estado=?,respuesta_parcial=?,pensamiento_parcial=?,estrategia=?,propietario_id=?,pid=?,hostname=?,boot_id=?,modo=?,comando_json=?,ultimo_progreso_en=?,ultimo_sondeo_en=?,actualizada_en=?,completada_en=?,error_codigo=?,error_detalle=?,cancelacion_solicitada=?,reintentos=? WHERE id=?`).run(n.modelo??null,n.conversacionId??null,n.estado,n.respuestaParcial,n.pensamientoParcial,n.estrategia??null,n.propietarioId,n.pid??null,n.hostname??null,n.bootId??null,n.modo,n.comandoJson??null,n.ultimoProgresoEn,n.ultimoSondeoEn??null,ahora,n.completadaEn??null,n.errorCodigo??null,n.errorDetalle??null,n.cancelacionSolicitada?1:0,n.reintentos,id)}
 obtener(id:string){const r=this.db.query('SELECT * FROM ejecuciones_chat_activas WHERE id=?').get(id);return r?mapear(r):null}
 listar(limite=100){return(this.db.query('SELECT * FROM ejecuciones_chat_activas ORDER BY creada_en DESC LIMIT ?').all(limite)as any[]).map(mapear)}
 anexarEvento(id:string,tipo:string,datos:Record<string,unknown>,ahora=Date.now()):EventoEjecucionChat{return this.db.transaction(()=>{const fila=this.db.query('UPDATE ejecuciones_chat_activas SET ultima_secuencia=ultima_secuencia+1 WHERE id=? RETURNING ultima_secuencia').get(id)as any;if(!fila)throw new Error(`Ejecución no encontrada: ${id}`);const sec=Number(fila.ultima_secuencia);this.db.query('INSERT INTO eventos_ejecucion_chat(ejecucion_id,secuencia,tipo,datos_json,creado_en) VALUES(?,?,?,?,?)').run(id,sec,tipo,JSON.stringify(datos),ahora);return{ejecucionId:id,secuencia:sec,tipo,datos,creadoEn:ahora}})()}
 listarEventos(id:string,desde=0){return(this.db.query('SELECT * FROM eventos_ejecucion_chat WHERE ejecucion_id=? AND secuencia>? ORDER BY secuencia').all(id,desde)as any[]).map(r=>({ejecucionId:r.ejecucion_id,secuencia:r.secuencia,tipo:r.tipo,datos:JSON.parse(r.datos_json),creadoEn:r.creado_en}))}
 solicitarCancelacion(id:string,ahora=Date.now()):'solicitada'|'ya_finalizada'|'no_encontrada'{const e=this.obtener(id);if(!e)return'no_encontrada';if(ESTADOS_TERMINALES.has(e.estado))return'ya_finalizada';this.actualizar(id,{cancelacionSolicitada:true},ahora);this.anexarEvento(id,'cancelacion_solicitada',{},ahora);return'solicitada'}
 adoptar(id:string,nuevo:{propietarioId:string;pid:number;hostname:string;bootId:string},ahora=Date.now()):boolean{const e=this.obtener(id);if(!e||!ESTADOS_REANUDABLES.has(e.estado))return false;const r=this.db.query(`UPDATE ejecuciones_chat_activas SET propietario_id=?,pid=?,hostname=?,boot_id=?,estado='esperando_respuesta',cancelacion_solicitada=0,error_codigo=NULL,error_detalle=NULL,actualizada_en=? WHERE id=? AND propietario_id=? AND estado=?`).run(nuevo.propietarioId,nuevo.pid,nuevo.hostname,nuevo.bootId,ahora,id,e.propietarioId,e.estado);if(r.changes===1)this.anexarEvento(id,'ejecucion_adoptada',{propietarioId:nuevo.propietarioId},ahora);return r.changes===1}
 marcarReanudable(id:string,ahora=Date.now()){this.actualizar(id,{estado:'reconectando',cancelacionSolicitada:false,errorCodigo:undefined,errorDetalle:undefined},ahora);this.anexarEvento(id,'reanudacion_solicitada',{},ahora)}
 reconciliarHuerfanas(esVivo:(e:EjecucionChatDurable)=>boolean,umbralMs=90_000,ahora=Date.now()):number{let n=0;for(const e of this.listar(10_000)){if(ESTADOS_TERMINALES.has(e.estado)||e.estado==='requiere_usuario')continue;const hb=e.ultimoSondeoEn??e.actualizadaEn;if(ahora-hb>umbralMs&&!esVivo(e)){this.actualizar(e.id,{estado:'reconectando',errorCodigo:'PROPIETARIO_MUERTO'},ahora);this.anexarEvento(e.id,'propietario_muerto',{},ahora);n++}}return n}
 compactar(id:string,conservarHeartbeats=10):number{const filas=this.db.query("SELECT rowid,secuencia FROM eventos_ejecucion_chat WHERE ejecucion_id=? AND tipo='heartbeat' ORDER BY secuencia DESC").all(id)as any[];const borrar=filas.slice(conservarHeartbeats);for(const f of borrar)this.db.query('DELETE FROM eventos_ejecucion_chat WHERE rowid=?').run(f.rowid);return borrar.length}
 limpiarTerminales(anterioresA:number):number{const ids=(this.db.query("SELECT id FROM ejecuciones_chat_activas WHERE completada_en IS NOT NULL AND completada_en<?").all(anterioresA)as any[]).map(x=>x.id);for(const id of ids)this.db.query('DELETE FROM ejecuciones_chat_activas WHERE id=?').run(id);this.db.query('DELETE FROM envios_idempotentes WHERE actualizado_en<?').run(anterioresA);return ids.length}
 metricas(){return{ejecuciones:Number((this.db.query('SELECT COUNT(*) n FROM ejecuciones_chat_activas').get()as any).n),activas:Number((this.db.query('SELECT COUNT(*) n FROM ejecuciones_chat_activas WHERE completada_en IS NULL').get()as any).n),eventos:Number((this.db.query('SELECT COUNT(*) n FROM eventos_ejecucion_chat').get()as any).n),enviosIdempotentes:Number((this.db.query('SELECT COUNT(*) n FROM envios_idempotentes').get()as any).n)}}
}
