import { describe, expect, test } from "bun:test";
import { QwenStreaming } from "../../src/proveedores/qwen/navegador/QwenStreaming";
import { DeepSeekStreaming } from "../../src/proveedores/deepseek/navegador/DeepSeekStreaming";
class Secuencia { i=0; constructor(private readonly estados:any[]){} async estaDisponible(){return true} async navegar(){} async evaluar<T>(_codigo?:string){return {value:this.estados[Math.min(this.i++,this.estados.length-1)] as T}} }
async function recoger(gen:AsyncGenerator<any>){const r=[];for await(const e of gen)r.push(e);return r}
describe("streaming",()=>{
 test("Qwen emite pensamiento, respuesta y fin",async()=>{let t=0;const tr=new Secuencia([{think:"Pensando",response:"",done:false,isAssistant:true,isError:false,errorMessage:""},{think:"Pensando",response:"OK",done:true,isAssistant:true,isError:false,errorMessage:""}]);const ev=await recoger(new QwenStreaming(tr,async()=>{},()=>t+=5000).observar());expect(ev.map(x=>x.tipo)).toEqual(["pensamiento","estado","respuesta","fin"])});
 test("DeepSeek emite respuesta y fin",async()=>{const tr=new Secuencia([{think:"",response:"OK",done:true,isAssistant:true,isError:false,errorMessage:""}]);const ev=await recoger(new DeepSeekStreaming(tr,async()=>{}).observar());expect(ev.map(x=>x.tipo)).toEqual(["respuesta","fin"])});
 test("DeepSeek falla tras reintentos",async()=>{const tr=new Secuencia([{think:"",response:"",done:false,isAssistant:true,isError:true,errorMessage:"ocupado"}]);expect(recoger(new DeepSeekStreaming(tr,async()=>{}).observar())).rejects.toThrow("ocupado")});
 test("DeepSeek usa IndexedDB si el DOM no expone respuesta",async()=>{const estados=[{think:"",response:"",done:false,isAssistant:true,isError:false,errorMessage:""}];class F extends Secuencia{override async evaluar<T>(c?:string){if(c?.includes("location.pathname"))return{value:"id" as T};if(c?.includes("indexedDB.open"))return{value:{data:{chat_session:{id:"id",title:"T"},chat_messages:[{role:"assistant",fragments:[{type:"RESPONSE",content:"OK"}]}]}} as T};return super.evaluar<T>(c)}}const ev=await recoger(new DeepSeekStreaming(new F(estados),async()=>{}).observar());expect(ev.map(x=>x.tipo)).toEqual(["respuesta","fin"])});
});
