export const SELECTORES_QWEN = {
  entrada: [
    'textarea[aria-label*="ayudarte" i]',
    'textarea[placeholder*="ayudarte" i]',
    'textarea[aria-label*="help" i]',
    '[role="textbox"][contenteditable="true"]',
    'textarea.message-input-textarea',
    'main textarea',
  ],
  enviarCandidatos: [
    'button[aria-label*="enviar" i]',
    'button[aria-label*="send" i]',
    'button[title*="enviar" i]',
    'button[title*="send" i]',
    'button.send-button',
    '.chat-prompt-send-button button',
  ],
  detenerCandidatos: [
    'button[aria-label*="detener" i]',
    'button[aria-label*="stop" i]',
    'button[title*="detener" i]',
    'button[title*="stop" i]',
    '[role="button"][aria-label*="stop" i]',
  ],
  mensaje: ['[data-message-role]', '[data-role]', '.qwen-chat-message', '[class*="chat-message-item"]', '[class*="message-item"]'],
  asistente: ['[data-message-role="assistant"]','[data-role="assistant"]','[data-testid*="assistant" i]','.qwen-chat-message-assistant','[class*="assistant"]'],
  contenido: ['[data-testid="assistant-content"]','[data-testid*="message-content" i]','article','.response-message-content','.qwen-markdown','[class*="response-message-content"]'],
  pensamiento: ['[data-testid*="thinking" i]','.qwen-thinking-status-card-title-text','.qwen-thinking-selector','[class*="thinking"]','[class*="tool-status"]'],
  toolbar: ['[role="toolbar"]','nav button[aria-label*="copiar" i]','button[aria-label*="copiar" i]','button[aria-label*="copy" i]','button[aria-label*="regenerar" i]','button[aria-label*="regenerate" i]'],
  textarea: 'textarea[aria-label*="ayudarte" i],textarea[placeholder*="ayudarte" i],[role="textbox"][contenteditable="true"],textarea.message-input-textarea,main textarea',
  enviar: 'button[aria-label*="enviar" i],button[aria-label*="send" i],button[title*="enviar" i],button[title*="send" i],button.send-button,.chat-prompt-send-button button',
  modelo: '[aria-label="Select Model"],[class*="model-selector"]',
  listaModelos: '[role="listbox"][aria-label="Modelos"],[role="listbox"]',
} as const;
